//
// Created by Oliver Hitz on 20.12.25.
//

#ifndef WIKIPEDIASTEP_DEPS_JSON_PAGEPARSER_H
#define WIKIPEDIASTEP_DEPS_JSON_PAGEPARSER_H


class Pageparser
{
};


#endif //WIKIPEDIASTEP_DEPS_JSON_PAGEPARSER_H